"""initial schema

Revision ID: 289d5fe89487
Revises: 
Create Date: 2026-08-17 13:53:57.499991
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '289d5fe89487'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=32), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_short_code'), ['short_code'], unique=True)

    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clicks_link_id'), ['link_id'], unique=False)
        batch_op.create_index('ix_clicks_link_time', ['link_id', 'clicked_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.drop_index('ix_clicks_link_time')
        batch_op.drop_index(batch_op.f('ix_clicks_link_id'))

    op.drop_table('clicks')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_short_code'))

    op.drop_table('links')
    # ### end Alembic commands ###
